// Generated by tool/gen_font_layouts.sh — do not edit by hand.
package com.malickabdullah.tessera.engine

import com.malickabdullah.tessera.R

internal val fontTable = listOf(
    FontFamilyInfo("dot", "Doto", listOf(
        FontFace(300, R.font.doto_300, R.layout.tc_doto_300, R.layout.tcc_doto_300),
        FontFace(400, R.font.doto_400, R.layout.tc_doto_400, R.layout.tcc_doto_400),
        FontFace(500, R.font.doto_500, R.layout.tc_doto_500, R.layout.tcc_doto_500),
        FontFace(700, R.font.doto_700, R.layout.tc_doto_700, R.layout.tcc_doto_700),
        FontFace(900, R.font.doto_900, R.layout.tc_doto_900, R.layout.tcc_doto_900),
    )),
    FontFamilyInfo("grotesk", "Space Grotesk", listOf(
        FontFace(300, R.font.space_grotesk_300, R.layout.tc_space_grotesk_300, R.layout.tcc_space_grotesk_300),
        FontFace(400, R.font.space_grotesk_400, R.layout.tc_space_grotesk_400, R.layout.tcc_space_grotesk_400),
        FontFace(500, R.font.space_grotesk_500, R.layout.tc_space_grotesk_500, R.layout.tcc_space_grotesk_500),
        FontFace(700, R.font.space_grotesk_700, R.layout.tc_space_grotesk_700, R.layout.tcc_space_grotesk_700),
    )),
    FontFamilyInfo("sans", "Inter Tight", listOf(
        FontFace(100, R.font.inter_tight_100, R.layout.tc_inter_tight_100, R.layout.tcc_inter_tight_100),
        FontFace(300, R.font.inter_tight_300, R.layout.tc_inter_tight_300, R.layout.tcc_inter_tight_300),
        FontFace(400, R.font.inter_tight_400, R.layout.tc_inter_tight_400, R.layout.tcc_inter_tight_400),
        FontFace(500, R.font.inter_tight_500, R.layout.tc_inter_tight_500, R.layout.tcc_inter_tight_500),
        FontFace(700, R.font.inter_tight_700, R.layout.tc_inter_tight_700, R.layout.tcc_inter_tight_700),
        FontFace(900, R.font.inter_tight_900, R.layout.tc_inter_tight_900, R.layout.tcc_inter_tight_900),
    )),
    FontFamilyInfo("mono", "JetBrains Mono", listOf(
        FontFace(300, R.font.jetbrains_mono_300, R.layout.tc_jetbrains_mono_300, R.layout.tcc_jetbrains_mono_300),
        FontFace(400, R.font.jetbrains_mono_400, R.layout.tc_jetbrains_mono_400, R.layout.tcc_jetbrains_mono_400),
        FontFace(500, R.font.jetbrains_mono_500, R.layout.tc_jetbrains_mono_500, R.layout.tcc_jetbrains_mono_500),
        FontFace(700, R.font.jetbrains_mono_700, R.layout.tc_jetbrains_mono_700, R.layout.tcc_jetbrains_mono_700),
    )),
    FontFamilyInfo("serif", "Instrument Serif", listOf(
        FontFace(400, R.font.instrument_serif_400, R.layout.tc_instrument_serif_400, R.layout.tcc_instrument_serif_400),
    )),
    FontFamilyInfo("condensed", "Oswald", listOf(
        FontFace(300, R.font.oswald_300, R.layout.tc_oswald_300, R.layout.tcc_oswald_300),
        FontFace(400, R.font.oswald_400, R.layout.tc_oswald_400, R.layout.tcc_oswald_400),
        FontFace(500, R.font.oswald_500, R.layout.tc_oswald_500, R.layout.tcc_oswald_500),
        FontFace(700, R.font.oswald_700, R.layout.tc_oswald_700, R.layout.tcc_oswald_700),
    )),
)
