#!/usr/bin/env bash
# Regenerates the TextClock layouts (one per bundled font face, plain and
# all-caps) and FontTable.kt from the faces listed below. TextClock cannot
# take a Typeface through RemoteViews, so each face needs its own layout.
set -euo pipefail
cd "$(dirname "$0")/.."
res=android/app/src/main/res/layout
kt=android/app/src/main/kotlin/com/malickabdullah/tessera/engine/FontTable.kt
faces=(
  "dot|Doto|doto|300,400,500,700,900"
  "grotesk|Space Grotesk|space_grotesk|300,400,500,700"
  "sans|Inter Tight|inter_tight|100,300,400,500,700,900"
  "mono|JetBrains Mono|jetbrains_mono|300,400,500,700"
  "serif|Instrument Serif|instrument_serif|400"
  "condensed|Oswald|oswald|300,400,500,700"
)
rm -f "$res"/tc_*.xml "$res"/tcc_*.xml
{
  echo "// Generated by tool/gen_font_layouts.sh — do not edit by hand."
  echo "package com.malickabdullah.tessera.engine"
  echo
  echo "import com.malickabdullah.tessera.R"
  echo
  echo "internal val fontTable = listOf("
} > "$kt"
for entry in "${faces[@]}"; do
  IFS='|' read -r key label file weights <<<"$entry"
  echo "    FontFamilyInfo(\"$key\", \"$label\", listOf(" >> "$kt"
  IFS=',' read -ra ws <<<"$weights"
  for w in "${ws[@]}"; do
    for caps in false true; do
      name="tc_${file}_${w}"; [[ $caps == true ]] && name="tcc_${file}_${w}"
      cat > "$res/$name.xml" <<EOF
<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tool/gen_font_layouts.sh -->
<TextClock xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/tc"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fontFamily="@font/${file}_${w}"
    android:includeFontPadding="false"
    android:maxLines="1"
    android:textAllCaps="$caps" />
EOF
    done
    echo "        FontFace($w, R.font.${file}_${w}, R.layout.tc_${file}_${w}, R.layout.tcc_${file}_${w})," >> "$kt"
  done
  echo "    ))," >> "$kt"
done
echo ")" >> "$kt"
